### ISSUE TITLE
Execution even after cancelling and execution icon not working on saved files

### ISSUE THREAD

**Issue by VIDUSHAG** [TheTrio/SlickPad#5] opened 2017-03-02 14:44 UTC
When I clicked on execution icon after saving code it didn't work. 
Bug.- after clicking execution icon and selecting Java when we cancel the execution and come back to editor it is still executing the code.

**Comment by TheTrio** [comment] 2017-03-03 14:23
@VIDUSHAG The 1st **Bug** is known by us. This is due to the fact that windows sometimes requires **admin permissions** to execute _batch programs_. **Until** this  bug is resolved, please try using 

> Edit << Java Program << Compile and Run

to execute java programs after saving.


Now for the more technical aspect, the bug is caused by The File [ControllerForRun.java](https://github.com/TheTrio/SlickPad/blob/master/src/com/company/ControllerForRun.java), due to this piece of code : 


     if (Main.bool_notify == true) {

            try {
                Formatter form = new Formatter("temp.java");
                form.format("%s", Main.myText);
                form.close();
                Thread thread = new Thread(this);
                thread.start();
                thread.join();
                Scanner s = new Scanner(System.in);
                FXMLLoader fxmlLoader = new FXMLLoader(Main.class.getResource("Popup.fxml"));
                try {
                    Parent root1 = (Parent) fxmlLoader.load();
                    Stage Pop;
                    Pop = new Stage();
                    Pop.initModality(Modality.APPLICATION_MODAL);
                    Pop.setTitle("Enter Value");
                    Pop.setScene(new Scene(root1));
                    Pop.setResizable(false);
                    Pop.showAndWait();

                } catch (Exception er) {


                }
                String className = Input.className;
                Formatter formatter = new Formatter("Jrun.bat");
                formatter.format("@echo off\n" + "\"" + SettingWindow.StringPathJava + "\\bin\\javac\"" + " temp.java\n" + "start cb_console_runner.exe java " + className);
                formatter.close();
                Process p = Runtime.getRuntime().exec("cmd /c \"" + SettingWindow.StringPathJava + "\\bin\\javac\"" + " temp.java");
                System.out.println("cmd /c \"" + SettingWindow.StringPathJava + "\\bin\\javac\"" + " temp.java");
                BufferedReader bufferedReader= new BufferedReader(new InputStreamReader(p.getErrorStream()));
                String as;
                String errorString = "Your Program had the following errors \n";
                boolean errorfound = false;
                while ((as = bufferedReader.readLine()) != null) {
                    errorString = errorString + "\n" + as;
                    errorfound = true;
                }
                System.out.println(errorfound);
                if(errorfound){
                    m.ChangeText(errorString);
                }else {
                    m.ChangeText("");
                    Thread thread1 = new Thread(){
                        public void run(){
                            try {
                                Runtime.getRuntime().exec("cmd /c  Jrun.bat");
                            } catch (IOException e1) {
                                e1.printStackTrace();
                            }
                        }
                    };
                    thread1.start();
                    thread1.join();
                }
            } catch (FileNotFoundException e1) {
                e1.printStackTrace();
            } catch (IOException e1) {
                e1.printStackTrace();
            } catch (InterruptedException e1) {
                e1.printStackTrace();
            }


        }else {

        }

The empty `else` statement causes this problem.
Also, for the execution after Cancel, it is caused by the Same File by the Lines :

    try {
            Parent root1 = (Parent) fxmlLoader.load();
            Stage Pop;
            Pop = new Stage();
            Pop.initModality(Modality.APPLICATION_MODAL);
            Pop.setTitle("Enter Value");
            Pop.setScene(new Scene(root1));
            Pop.setResizable(false);
            Pop.showAndWait();

    } catch (Exception er) {


    }
    String className = Input.className; 

This line executed no whatever what you enter, or even press cancel. This is a very petty problem, and can be fixed by adding the following line before `String className = Input.className; `

    if(className!=null){
          //Rest Of Code
    }
We, @The-StRaCkEr and **Me**, thank you for bringing the Second Bug into notice. We will work hard to resolve your issues. Please pardon us for any inconvenience caused by this Bug to you.

# Regards, 
## Shashwat,
#### Co-Founder - TheTrio

**Closed as completed** 2017-12-21 15:11 UTC
